theme: jekyll-theme-minimal
title: Cinematic Archetypes: Decoding Societal Preferences
description: DataStory about 
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
